---
title: Projects
---
## Rural Karnataka Schools Dropout Analysis |R 
  <a href="https://github.com/krmh04/Karnataka-Rural-Secondary-Schools-Analysis" target="_blank">Code</a><br>    

- Performed an extensive analysis of dropout rate in rural secondary schools of Karnataka using a Fixed effects model to control for time-invariant factors.
- Involved identifying key factors related to the school infrastructure affecting the dropout rate ,predicting the future dropout rate and suggesting policy measures to reduce them.
## ExplainAI | Python, Streamlit,Deta Space

  <a href="https://github.com/krmh04/ExplainAI" target="_blank">Code</a><br>    

 
- Developed a web application to quickly summarize large blocks of text and videos/podcasts
- It also allows the user to summarize the text from web links as well as from locally uploaded PDF files.
- Used the Open AI API and Deepgram API for summarizing/transcribing the text and the Courier Email API to send emails
 
 


## GeoConnect | MongoDB,Express.js,React,Node.js

 
  <a href="https://github.com/krmh04/GeoConnect" target="_blank">Code</a><br>

- Developed a web application enabling users to mark their places of interest or visited locations on the world map
- Stored/Fetched the data of the users using the MongoDB Atlas platform
 
 
